### ISSUE TITLE
Remove the references to media articles

### ISSUE THREAD

**Issue by conormuldoon** [drop-ice/dear-github-2.0#128]
I would sign this, as I don't like Trump's ICE policy, but the open letter references media articles that I don't know for sure whether they are true or false. You would get more support if the letter was worded differently and the references to media articles were left out.

**Comment by drop-ice** [comment]
@conormuldoon we included those links so visitors that are unfamiliar with ICE and related government policies could learn more.

**Comment by m-cat** [comment]
Well, the references seem to mostly come from clear-as-day propaganda outlets like The Atlantic and NYT.

For example, [here](https://www.nytimes.com/2019/12/04/us/politics/george-nader-ahmad-khawaja.html) is a recent article from the NYT about a man charged with funneling money to Clinton. Wait, why is a photo of Trump under that headline? Why isn't Clinton mentioned in the headline, like Trump is in all the anti-Trump articles?

[Here](https://i.redd.it/tkyf0079rrp21.jpg) is my personal favorite. They don't call it "fake news" for nothing, you know.

It would help your cause if you had any references to actual reputable sources, rather than thinly-veiled propaganda outlets which are known for blatantly lying, like when they slandered Kavanaugh with fabricated sexual assault claims.

It is really sad that some people are so ignorant that they need this state of affairs explicitly spelled out for them, even though it's been going on for years and particularly obvious since 2015.

**Comment by mr21** [comment]
yeah yeah...
_"All the newspapers in the world except Fox and friends are PrOpAgAnDa and trump is perfect."_

**Comment by m-cat** [comment]
Yes, propaganda. Don't be a [fool](https://en.wikipedia.org/wiki/Useful_idiot).
